spring:
  application:
    name: auth-azure
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: masterkey
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: ${TENANT_ID}
        registration:
          azure:
            provider: azure
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile